# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [2]:
import numpy as np
# formula = weight / (height**2) * 730
h = [69, 70, 71, 72, 73, 74, 75]
w = [110, 120, 130, 140, 150, 160, 170]
#Using equation above and Multi-dimensional Arrays from lesson
# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]
def BMI(h,w):
    return np.array(w)/(np.array(h)**2) * 730
BMI(h,w)



array([16.86620458, 17.87755102, 18.82562984, 19.71450617, 20.54794521,
       21.32943755, 22.06222222])

### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [19]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
# def makeMatrix(low,high,shape,data_type = float): -- Example
#     pass
#from lesson ICE # 2 and Complex Indexing & Assinging random sampling
def matriX(low=1, high=20, row=4, column=4, data_type = float):
    m = np.random.uniform(low,high,(row,column)).astype(data_type)
    return m
matriX()

array([[ 6.56355497,  1.15940378, 10.8998216 ,  3.39780725],
       [18.83458103, 11.95281963, 14.80756266,  6.65997285],
       [ 5.12452395, 10.68830213,  8.73285487,  6.35481073],
       [18.47728917,  8.46219563,  7.74276319, 13.62098253]])

### #3 - Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [26]:
import csv
import numpy as np

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]
#Test to make sure you have the correct data from lesson loading csv from data
def sports_data(filename, d=','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data

rsox2017 = sports_data('redsox_2017_hitting.txt')
rsox2018 = sports_data('redsox_2018_hitting.txt')

n1 = rsox2017['Name'][:10]
slug1 = rsox2017['SLG'][:10]

n2 = rsox2018['Name'][:10]
slug2 = rsox2018['SLG'][:10]

print(slug1, slug2)
#after seeing results:
print('Bos had better year in 2017!')

[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354] [0.279 0.433 0.388 0.522 0.433 0.465 0.403 0.64  0.629 0.411]
Bos had better year in 2017!


In [1]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""





'\nExample Result - Not the actual result\nBoston 18 had more SLG in 2018\n[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333\n 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]\n'